services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./php:/var/www/html/app
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
      - ./.htaccess:/var/www/html/.htaccess

  frontend:
    build:
      context: .
      target: 'develop-stage'
      dockerfile: ./app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - './app:/app'
      - './node_modules:/node_modules'
      - './package.json:/package.json'
      - './package-lock.json:/package-lock.json'
    command: /bin/sh -c "npm run dev"
    tty: true

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_KEY_BUFFER_SIZE: 16M
      MYSQL_READ_BUFFER_SIZE: 2M
      MYSQL_SORT_BUFFER_SIZE: 1M
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
