version: '3'

services:
  todo-app:
    build: /app
     # dockerfile: app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php-backend
    #volumes:
      #- /node_modules
      #- ./:/app
      #- /php
      #- /node_modules

  php-backend:
    build:
      dockerfile: php/Dockerfile
    ports:
      - "8080:80"
    #volumes:
      #- /php:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo
      - DB_USERNAME=todo-app-user
      - DB_PASSWORD=default

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo-app-user
      - MYSQL_PASSWORD=default
      - MYSQL_ROOT_PASSWORD=default
    ports:
      - "3306:3306"