version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./php:/var/www/html/app
      #- ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
      - ./.htaccess:/var/www/html/.htaccess
    networks:
      - internal

  frontend:
    build:
      context: .
      target: 'develop-stage'
      dockerfile: ./app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm run dev"
    tty: true
    networks:
      - internal

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo-app-user
      - MYSQL_PASSWORD=default
      - MYSQL_ROOT_PASSWORD=default
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: default
      UPLOAD_LIMIT: 300M
