version: '3'
services:
  todo-app:
    image: nginx:alpine
    volumes:
      - ./etc/nginx/conf.d/default.conf.nginx:/etc/nginx/conf.d/default.conf
      - '.:/app'
      - '/app/node_modules'
    ports:
       - 81:80
    build:
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend

  frontend:
    image: node:current-alpine
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    environment:
      NODE_ENV: development
    command: "npm run serve"

  backend:
    build:
      context: dockerize/backend
    volumes:
      - ./backend:/app
      - ./etc/php:/usr/local/etc/php/local.conf.d/
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./etc/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql